# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
- name: gradle update checker
  # You may pin to the exact commit or the version.
  # uses: MeilCli/gradle-update-check-action@dd1c040b6ff1ae578af752562a205ee177df7f98
  uses: MeilCli/gradle-update-check-action@v3.0.0
  with:
    # target root build.gradle files
    build_gradle_files: # optional
    # skip automally add dependency of gradle-versions-plugin
    skip_plugin_dependency: # optional
    # version check revision
    revision: # optional
    # output text style, value: short or long
    output_text_style: # default is short
